-- =====================================================
-- SCRIPT CRUD COMPLETO - FASTDRIVE
-- Tablas Tipo: ROL, ESTADO, UNIVERSIDAD
-- Tablas Fuertes: PERFIL, MENU
-- =====================================================

-- =====================================================
-- TABLA ROL
-- =====================================================

-- Ver todos los roles
SELECT * FROM ROL ORDER BY ID_ROL;

-- Ver un rol específico
SELECT * FROM ROL WHERE ID_ROL = 1;
SELECT * FROM ROL WHERE NOMBRE_ROL = 'ADMINISTRADOR';

-- Insertar un rol
INSERT INTO ROL (NOMBRE_ROL) VALUES ('NUEVO_ROL');

-- Actualizar un rol
UPDATE ROL SET NOMBRE_ROL = 'NOMBRE_NUEVO' WHERE ID_ROL = 1;

-- Eliminar un rol (solo si no tiene perfiles asociados)
DELETE FROM ROL WHERE ID_ROL = 1;

-- Ver cuántos perfiles tiene cada rol
SELECT R.NOMBRE_ROL, COUNT(P.CODIGO_PERFIL) AS TOTAL_PERFILES
FROM ROL R
LEFT JOIN PERFIL P ON P.ID_ROL = R.ID_ROL
GROUP BY R.NOMBRE_ROL
ORDER BY R.NOMBRE_ROL;

-- TABLA ESTADO

-- Ver todos los estados
SELECT * FROM ESTADO ORDER BY CATEGORIA, NOMBRE_ESTADO;

-- Ver estados por categoría
SELECT * FROM ESTADO WHERE CATEGORIA = 'CUENTA';
SELECT * FROM ESTADO WHERE CATEGORIA = 'VERIFICACION';
SELECT * FROM ESTADO WHERE CATEGORIA = 'CONDUCTOR';
SELECT * FROM ESTADO WHERE CATEGORIA = 'VEHICULO';
SELECT * FROM ESTADO WHERE CATEGORIA = 'VIAJE';
SELECT * FROM ESTADO WHERE CATEGORIA = 'RESERVA';
SELECT * FROM ESTADO WHERE CATEGORIA = 'RUTA';
SELECT * FROM ESTADO WHERE CATEGORIA = 'VINCULACION';
SELECT * FROM ESTADO WHERE CATEGORIA = 'USUARIO';

-- Ver un estado específico
SELECT * FROM ESTADO WHERE ID_ESTADO = 1;
SELECT * FROM ESTADO WHERE NOMBRE_ESTADO = 'ACTIVO' AND CATEGORIA = 'CUENTA';

-- Contar estados por categoría
SELECT CATEGORIA, COUNT(*) AS TOTAL
FROM ESTADO
GROUP BY CATEGORIA
ORDER BY CATEGORIA;

-- Insertar un estado
INSERT INTO ESTADO (NOMBRE_ESTADO, CATEGORIA) VALUES ('NUEVO_ESTADO', 'CUENTA');

-- Actualizar un estado
UPDATE ESTADO SET NOMBRE_ESTADO = 'NUEVO_NOMBRE' WHERE ID_ESTADO = 1;
UPDATE ESTADO SET CATEGORIA = 'NUEVA_CATEGORIA' WHERE ID_ESTADO = 1;
UPDATE ESTADO SET NOMBRE_ESTADO = 'NUEVO_NOMBRE', CATEGORIA = 'NUEVA_CATEGORIA' WHERE ID_ESTADO = 1;

-- Eliminar un estado (solo si no tiene usuarios asociados)
DELETE FROM ESTADO WHERE ID_ESTADO = 1;

-- TABLA UNIVERSIDAD


-- Ver todas las universidades
SELECT * FROM UNIVERSIDAD ORDER BY NOMBRE_UNI;

-- Ver una universidad específica
SELECT * FROM UNIVERSIDAD WHERE NIT_UNI = ' 890.980.040-8';
SELECT * FROM UNIVERSIDAD WHERE NOMBRE_UNI LIKE '%Antioquia%';

-- Ver universidades con su dominio de correo
SELECT NIT_UNI, NOMBRE_UNI, DOMINIO_CORREO_UNI
FROM UNIVERSIDAD
ORDER BY NOMBRE_UNI;

-- Ver universidades con coordenadas
SELECT NOMBRE_UNI, DIRECCION_LATITUD_UNI, DIRECCION_LONGITUD_UNI
FROM UNIVERSIDAD
ORDER BY NOMBRE_UNI;

-- Ver cuántos estudiantes tiene cada universidad
SELECT U.NOMBRE_UNI, COUNT(UE.ID_USER) AS TOTAL_ESTUDIANTES
FROM UNIVERSIDAD U
LEFT JOIN UNIVERSIDAD_ESTUDIANTE UE ON UE.NIT_UNI = U.NIT_UNI
GROUP BY U.NOMBRE_UNI
ORDER BY TOTAL_ESTUDIANTES DESC;

-- Insertar una universidad
INSERT INTO UNIVERSIDAD (NIT_UNI, NOMBRE_UNI, DOMINIO_CORREO_UNI, DIRECCION_LONGITUD_UNI, DIRECCION_LATITUD_UNI)
VALUES ('000.000.000-0', 'Nueva Universidad', 'nuevauni.edu.co', -75.56446, 6.31806);

-- Actualizar una universidad
UPDATE UNIVERSIDAD SET NOMBRE_UNI = 'Nuevo Nombre' WHERE NIT_UNI = '000.000.000-0';
UPDATE UNIVERSIDAD SET DOMINIO_CORREO_UNI = 'nuevo.edu.co' WHERE NIT_UNI = '000.000.000-0';
UPDATE UNIVERSIDAD SET DIRECCION_LATITUD_UNI = 6.31806, DIRECCION_LONGITUD_UNI = -75.56446 WHERE NIT_UNI = '000.000.000-0';

-- Eliminar una universidad (solo si no tiene estudiantes asociados)
DELETE FROM UNIVERSIDAD WHERE NIT_UNI = '000.000.000-0';

-- =====================================================
-- TABLA PERFIL

-- Ver todos los perfiles
SELECT * FROM PERFIL ORDER BY CODIGO_PERFIL;

-- Ver perfiles con su rol
SELECT P.CODIGO_PERFIL, P.NOMBRE_PERFIL, R.NOMBRE_ROL
FROM PERFIL P
JOIN ROL R ON R.ID_ROL = P.ID_ROL
ORDER BY R.NOMBRE_ROL, P.NOMBRE_PERFIL;

-- Ver perfiles por rol
SELECT P.CODIGO_PERFIL, P.NOMBRE_PERFIL
FROM PERFIL P
JOIN ROL R ON R.ID_ROL = P.ID_ROL
WHERE R.NOMBRE_ROL = 'ESTUDIANTE';

-- Ver un perfil específico
SELECT * FROM PERFIL WHERE CODIGO_PERFIL = 1;
SELECT * FROM PERFIL WHERE NOMBRE_PERFIL = 'AdministradorGeneral';

-- Ver cuántos usuarios tiene cada perfil
SELECT P.NOMBRE_PERFIL, R.NOMBRE_ROL, COUNT(U.ID_USER) AS TOTAL_USUARIOS
FROM PERFIL P
JOIN ROL R ON R.ID_ROL = P.ID_ROL
LEFT JOIN USUARIO U ON U.CODIGO_PERFIL = P.CODIGO_PERFIL
GROUP BY P.NOMBRE_PERFIL, R.NOMBRE_ROL
ORDER BY TOTAL_USUARIOS DESC;

-- Insertar un perfil
INSERT INTO PERFIL (NOMBRE_PERFIL, ID_ROL) VALUES ('Nuevo Perfil', 3);

-- Actualizar un perfil
UPDATE PERFIL SET NOMBRE_PERFIL = 'Nuevo Nombre' WHERE CODIGO_PERFIL = 1;
UPDATE PERFIL SET ID_ROL = 2 WHERE CODIGO_PERFIL = 1;

-- Eliminar un perfil (solo si no tiene usuarios asociados)
DELETE FROM PERFIL WHERE CODIGO_PERFIL = 1;

-- =====================================================
-- TABLA MENU
-- =====================================================

-- Ver todos los menús
SELECT * FROM MENU ORDER BY CODIGO_MENU;

-- Ver menús con su padre
SELECT M.CODIGO_MENU, M.NOMBRE_MENU, M.URL_MENU,
       MP.NOMBRE_MENU AS MENU_PADRE
FROM MENU M
LEFT JOIN MENU MP ON MP.CODIGO_MENU = M.MENU_PADRE_CODIGO
ORDER BY M.CODIGO_MENU;

-- Ver solo menús padre (sin padre)
SELECT * FROM MENU WHERE MENU_PADRE_CODIGO IS NULL;

-- Ver submenús de un menú padre
SELECT * FROM MENU WHERE MENU_PADRE_CODIGO = 'M001';

-- Ver menús con sus permisos por perfil
SELECT M.NOMBRE_MENU, P.NOMBRE_PERFIL,
       MP.PUEDE_CREAR, MP.PUEDE_LEER,
       MP.PUEDE_ACTUALIZAR, MP.PUEDE_ELIMINAR
FROM MENU_PERMISO MP
JOIN MENU M ON M.CODIGO_MENU = MP.CODIGO_MENU
JOIN PERFIL P ON P.CODIGO_PERFIL = MP.CODIGO_PERFIL
ORDER BY M.NOMBRE_MENU, P.NOMBRE_PERFIL;

-- Insertar un menú sin padre
INSERT INTO MENU (CODIGO_MENU, URL_MENU, NOMBRE_MENU)
VALUES ('M006', '/nueva-seccion', 'Nueva Sección');

-- Insertar un submenú con padre
INSERT INTO MENU (CODIGO_MENU, URL_MENU, NOMBRE_MENU, MENU_PADRE_CODIGO)
VALUES ('M061', '/nueva-seccion/detalle', 'Detalle', 'M006');

-- Actualizar un menú
UPDATE MENU SET NOMBRE_MENU = 'Nuevo Nombre' WHERE CODIGO_MENU = 'M006';
UPDATE MENU SET URL_MENU = '/nueva-url' WHERE CODIGO_MENU = 'M006';
UPDATE MENU SET MENU_PADRE_CODIGO = 'M001' WHERE CODIGO_MENU = 'M006';

-- Eliminar un menú (primero eliminar permisos asociados)
DELETE FROM MENU_PERMISO WHERE CODIGO_MENU = 'M006';
DELETE FROM MENU WHERE CODIGO_MENU = 'M006';

-- =====================================================
-- CONSULTAS ÚTILES GENERALES
-- =====================================================

-- Ver todos los usuarios con su perfil, rol y estado
SELECT U.ID_USER, U.NOMBRE_USER, U.APELLIDO_USER,
       U.CORREO_PERSONAL_USER, P.NOMBRE_PERFIL,
       R.NOMBRE_ROL, E.NOMBRE_ESTADO AS ESTADO_CUENTA
FROM USUARIO U
JOIN PERFIL P ON P.CODIGO_PERFIL = U.CODIGO_PERFIL
JOIN ROL R ON R.ID_ROL = P.ID_ROL
JOIN ESTADO E ON E.ID_ESTADO = U.ID_ESTADO_CUENTA
ORDER BY U.ID_USER;

-- Ver usuarios pendientes de aprobación
SELECT U.ID_USER, U.NOMBRE_USER, U.APELLIDO_USER,
       U.CORREO_PERSONAL_USER, P.NOMBRE_PERFIL, R.NOMBRE_ROL
FROM USUARIO U
JOIN PERFIL P ON P.CODIGO_PERFIL = U.CODIGO_PERFIL
JOIN ROL R ON R.ID_ROL = P.ID_ROL
JOIN ESTADO E ON E.ID_ESTADO = U.ID_ESTADO_CUENTA
WHERE E.NOMBRE_ESTADO = 'PENDIENTE' AND E.CATEGORIA = 'VERIFICACION'
ORDER BY U.ID_USER;

-- Ver estudiantes con sus universidades
SELECT U.NOMBRE_USER, U.APELLIDO_USER,
       U.DOCUMENTO_IDENTIDAD_USER,
       UN.NOMBRE_UNI,
       UE.CORREO_INSTITUCIONAL_UNE
FROM UNIVERSIDAD_ESTUDIANTE UE
JOIN USUARIO U ON U.ID_USER = UE.ID_USER
JOIN UNIVERSIDAD UN ON UN.NIT_UNI = UE.NIT_UNI
ORDER BY U.APELLIDO_USER;

-- Ver conductores con su vehículo
SELECT U.NOMBRE_USER, U.APELLIDO_USER,
       C.NUMERO_LICENCIA, C.FECHA_VENCIMIENTO_LICENCIA,
       V.PLACA_VEH, V.MARCA_VEH, V.MODELO_VEH,
       V.TOTAL_CUPOS_VEH
FROM CONDUCTOR C
JOIN USUARIO U ON U.ID_USER = C.ID_USER
JOIN VEHICULO V ON V.ID_USER = C.ID_USER
ORDER BY U.APELLIDO_USER;